source 'https://rubygems.org'
ruby '2.6.5'
gem 'sinatra', '~> 2.0.1', require: false

group :test do
  gem 'activemodel'
  gem 'rspec'
  gem 'rack-test'
  gem 'codacy-coverage', :require => false
end
