source 'https://rubygems.org'
ruby '2.7.6'
gem 'sinatra', '~> 2.2.3', require: false

group :test do
  gem 'activemodel', '~> 5.2.4'
  gem 'rspec', '~> 3.10'
  gem 'rack-test'
  gem 'codacy-coverage', :require => false
end
